### ISSUE TITLE
Instrucciones

### ISSUE THREAD

**Issue by iuria21** [adai183/ULMFiT_es#1]
Hola, primero gracias por tu trabajo y tu post de Medium. Estoy intentando  hacer lo mismo que tú, pero no encuentro cuáles son los pasos entre todos los notebooks y archivos. Por otra parte podrías especificar qué es cada archivo? (sobre todo los que faltan, los de `/tmp/` y los de `/LM_fine_tune/`. No tengo acceso al dataset de los tweets, por lo que me gustaría probarlo con otro dataset, pero no consigo entender cómo utilizar la repo y qué es cada archivo 😅

Un saludo y gracias!

**Comment by adai183** [comment]
Hola!
Perdona. No llegue a documentar este repo. Que desastre.
Te recomiendo que eches un vistazo a este [repo](https://github.com/n-waves/ulmfit-multilingual)
Está bien documentado y Sebastian Ruder ha estado involucrado en el proceso. Y lo mas importante usa fasta.ai 1.0. Lo mio usa 0.7. Muy antiguo ya. Jajajaja

Tambien esta este thread en el forum de fast.ai donde puedes hacer preguntas.
https://forums.fast.ai/t/multilingual-ulmfit/28117/14

**Comment by iuria21** [comment]
vale, muchas gracias, había visto esa repo pero me pareció que tú lo hacías más simple... Pero bueno, he conseguido hacer lo que quería con este que me has mandado, así que muchas gracias!
